<?php

/**
 * Clear varnish cache when news are published. (Hardcoded!! very un-dynamic!)
 *
 * Implements hook_update().
 */
function svendborg_nyheder_node_update($node) {
  _svendborg_nyheder_clear_varnish($node);
}

/**
 * Implements hook_node_insert().
 */
function svendborg_nyheder_node_insert($node) {
  _svendborg_nyheder_clear_varnish($node);
}

/**
 * Sends a clear cache command to varnish for published news articles
 */
function _svendborg_nyheder_clear_varnish($node) {
  if ($node->type == 'os2web_base_news') {
    if ($node->status == 1) {
      // Node is a published news article. Get hostname and clear cache on URL /nyheder

      global $base_url;
      $temp = parse_url($base_url);
      $host = $temp['host'];
      $url = '^/nyheder$|^/borger|^/erhverv$|^/nyheder/hoeringer-og-afgoerelser$';

      varnish_purge($host, $url);
      drupal_set_message(t('Varnish cachen ryddet for nyhedssiderne'));
      watchdog('svendborg_nyheder', 'Cleared cache for ' . $url . ' on ' . $host);
    }
  }
}